// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"text.io/ent/collection"
	"text.io/ent/link"
	"text.io/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	collectionFields := schema.Collection{}.Fields()
	_ = collectionFields
	// collectionDescFingerprint is the schema descriptor for fingerprint field.
	collectionDescFingerprint := collectionFields[0].Descriptor()
	// collection.FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	collection.FingerprintValidator = collectionDescFingerprint.Validators[0].(func(string) error)
	// collectionDescTitle is the schema descriptor for title field.
	collectionDescTitle := collectionFields[1].Descriptor()
	// collection.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	collection.TitleValidator = collectionDescTitle.Validators[0].(func(string) error)
	// collectionDescPublished is the schema descriptor for published field.
	collectionDescPublished := collectionFields[2].Descriptor()
	// collection.DefaultPublished holds the default value on creation for the published field.
	collection.DefaultPublished = collectionDescPublished.Default.(bool)
	// collectionDescCreatedAt is the schema descriptor for created_at field.
	collectionDescCreatedAt := collectionFields[5].Descriptor()
	// collection.DefaultCreatedAt holds the default value on creation for the created_at field.
	collection.DefaultCreatedAt = collectionDescCreatedAt.Default.(func() time.Time)
	linkFields := schema.Link{}.Fields()
	_ = linkFields
	// linkDescFingerprint is the schema descriptor for fingerprint field.
	linkDescFingerprint := linkFields[0].Descriptor()
	// link.FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	link.FingerprintValidator = linkDescFingerprint.Validators[0].(func(string) error)
	// linkDescURL is the schema descriptor for url field.
	linkDescURL := linkFields[2].Descriptor()
	// link.URLValidator is a validator for the "url" field. It is called by the builders before save.
	link.URLValidator = linkDescURL.Validators[0].(func(string) error)
	// linkDescCreatedAt is the schema descriptor for created_at field.
	linkDescCreatedAt := linkFields[4].Descriptor()
	// link.DefaultCreatedAt holds the default value on creation for the created_at field.
	link.DefaultCreatedAt = linkDescCreatedAt.Default.(func() time.Time)
}
