// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)
